# 演習課題 (後期)

## 第1回

### 問題1

LLM を使った作りたいアプリを具体的に述べなさい。

Teamsやカレンダーなどのアプリと連携した、リマインダーアプリ

### 問題2

画像生成モデルを使った作りたいアプリを具体的に述べなさい。

顔写真と髪型を入力し、元の顔写真から髪型を変更した画像を生成するアプリ

### 問題3

提供されている LLM のサービスをひとつ選び、それについて調査しなさい。調査結果を以下にまとめなさい。

<br>

< ヒント >
- 開発元
- モデル
- 安全性
- Temperture の設定

| 観点        | 内容                                                                                                                                               |
|-------------|----------------------------------------------------------------------------------------------------------------------------------------------------|
| 開発元      | Perplexity AI, Inc.（米国カリフォルニア州、2022年設立、OpenAI・Meta等出身者チーム）                                            |
| モデル      | GPT-4、Claude 3、Gemini、独自モデル。「Perplexity Pro Search」「Deep Research」など用途別選択可                              |
| 安全性      | 情報源の自動記載／ハルシネーション少／個人情報は第三者非共有、削除時30日保持、機密入力は非推奨                              |
| Temperature | 出力の多様性・創造性を指定（0で保守的、1で多様性最大）、用途に応じて調整可能                                                     |

### 問題4

問題3で選んだ LLM を使って hallucination を起こし、それを記しなさい。また、hallucination が生じた理由を推測しなさい。

### 問題5

提供されている画像生成のサービスをひとつ選び、それについて調査しなさい。調査結果を以下にまとめなさい。

### 問題6

問題5で選んだ画像生成のサービスで生成した画像について、ステレオタイプや偏見が含まれていないかを確認しなさい。もしあれば、その理由について推測しなさい。

## 第2回

### 問題1

`rnn.ipynb` のコードを理解しながら確かめなさい。

### 問題2

`rnn.ipynb` において、train データと validation データに対する学習曲線(損失関数)をプロットしなさい。

In [ ]:
import matplotlib.pyplot as plt

plt.figure(figsize=(8, 5))
plt.plot(train_losses, label='Train Loss')
plt.plot(val_losses, label='Validation Loss')
plt.xlabel('Epoch')
plt.ylabel('Loss (MSE)')
plt.title('Training and Validation Loss Curve')
plt.legend()
plt.grid(True)
plt.show()

### 問題3

`rnn.ipynb` において、予測値と実際の値をプロットしなさい。

In [ ]:
plt.figure(figsize=(10, 6))
plt.plot(test_actuals, label='Actual Price')
plt.plot(test_predictions, label='Predicted Price')
plt.xlabel('Time Step')
plt.ylabel('Dow Jones Price')
plt.title('RNN Prediction vs Actual (Test Set)')
plt.legend()
plt.grid(True)
plt.show()

### 問題4

`rnn.ipynb` にある RNN のハイパーパラメータを変更して、モデルの精度を高めなさい。

In [ ]:
# ハイパーパラメータを変更して再学習
HIDDEN_SIZE = 64  # 隠れ層のサイズを増やす
NUM_LAYERS = 2    # RNN層を2層に
BATCH_SIZE = 32   # バッチサイズを増やす
NUM_EPOCHS = 20   # エポック数を増やす
LEARNING_RATE = 0.005  # 学習率を調整

# データローダーの再作成
train_loader = DataLoader(train_dataset, batch_size=BATCH_SIZE, shuffle=False)
val_loader = DataLoader(val_dataset, batch_size=BATCH_SIZE, shuffle=False)
test_loader = DataLoader(test_dataset, batch_size=BATCH_SIZE, shuffle=False)

# モデルの再定義
model = SimpleRNN(INPUT_SIZE, HIDDEN_SIZE, NUM_LAYERS, OUTPUT_SIZE)
optimizer = torch.optim.Adam(model.parameters(), lr=LEARNING_RATE)

train_losses = []
val_losses = []

print("Training Start (Hyperparameter Tuning)")
for epoch in range(NUM_EPOCHS):
    model.train()
    total_train_loss = 0

    for X_batch, y_batch in train_loader:
        outputs = model(X_batch)
        loss = criterion(outputs, y_batch)

        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

        total_train_loss += loss.item()

    avg_train_loss = total_train_loss / len(train_loader)

    model.eval()
    total_val_loss = 0
    with torch.no_grad():
        for X_batch_val, y_batch_val in val_loader:
            outputs_val = model(X_batch_val)
            val_loss = criterion(outputs_val, y_batch_val)
            total_val_loss += val_loss.item()

    avg_val_loss = total_val_loss / len(val_loader)

    train_losses.append(avg_train_loss)
    val_losses.append(avg_val_loss)

    print(f"Epoch [{epoch+1}/{NUM_EPOCHS}]  Train Loss: {avg_train_loss:.4f},  Val Loss: {avg_val_loss:.4f}")

print("Training Complete (Hyperparameter Tuning)")

test_loss, test_predictions, test_actuals = evaluate_model(model, test_loader)
print(f"Test Loss after tuning: {test_loss:.4f}")

### 問題5

`rnn.ipynb` では株価指数の予測を行っているが、他の時系列データを使ってモデルを構築して、時系列予測を行いなさい。

## 第3回

### 問題1

`tiktoken` を使って、英語や日本語の文章をトークン化しなさい。また、単語とトークンに違いがあるかを確認したりして、その結果を考察しなさい。

In [1]:
# example

import tiktoken

text = "Hello World!"

enc = tiktoken.get_encoding("cl100k_base")

tokens = enc.encode(text)
print("Tokens:", tokens)

decoded = enc.decode(tokens)
print("Decoded:", decoded)

token_strings = [enc.decode([t]) for t in tokens]
print("Token pieces:", token_strings)

Tokens: [9906, 4435, 0]
Decoded: Hello World!
Token pieces: ['Hello', ' World', '!']


In [ ]:
# 英語と日本語の文章を用意
english_text = "I love natural language processing."
japanese_text = "私は自然言語処理が大好きです。"

# トークン化
english_tokens = enc.encode(english_text)
japanese_tokens = enc.encode(japanese_text)

# トークンを文字列に変換
english_token_strings = [enc.decode([t]) for t in english_tokens]
japanese_token_strings = [enc.decode([t]) for t in japanese_tokens]

print("English text:", english_text)
print("English tokens:", english_tokens)
print("English token pieces:", english_token_strings)
print("Number of words (English):", len(english_text.split()))
print("Number of tokens (English):", len(english_tokens))

print("\nJapanese text:", japanese_text)
print("Japanese tokens:", japanese_tokens)
print("Japanese token pieces:", japanese_token_strings)
print("Number of words (Japanese):", len(japanese_text.split()))
print("Number of tokens (Japanese):", len(japanese_tokens))

# 考察
print("\n考察:")
print("単語数とトークン数は一致しない。トークンは単語より細かい単位で分割されるため、特に日本語では単語分割が困難なためトークン数が多くなると考えられる。")

English text: I love natural language processing.
English tokens: [40, 3021, 5933, 4221, 8863, 13]
English token pieces: ['I', ' love', ' natural', ' language', ' processing', '.']
Number of words (English): 5
Number of tokens (English): 6

Japanese text: 私は自然言語処理が大好きです。
Japanese tokens: [86127, 15682, 37026, 61994, 78244, 45918, 252, 12870, 99, 22649, 29295, 27384, 53901, 50834, 38641, 1811]
Japanese token pieces: ['私', 'は', '自', '然', '言', '�', '�', '�', '�', '理', 'が', '大', '好', 'き', 'です', '。']
Number of words (Japanese): 1
Number of tokens (Japanese): 16

考察:
単語数とトークン数は一致しない。トークンは単語より細かい単位（サブワードや文字列断片）で分割されるため、特に日本語では単語分割が困難なためトークン数が多くなることがある。


### 問題2

"Attention Is All You Need" の論文の Abstract と Introduction, Conclusion を読んで、わからない概念や単語を調べ、内容を確認しなさい。


Attention Is All You Need: https://arxiv.org/abs/1706.03762

### 問題3

次の2つのベクトルの内積を求めよ。なお、LaTeX 表記で答えること。

$$
{a} = 
\begin{pmatrix}
3 \\
4
\end{pmatrix}, \quad
{b} = 
\begin{pmatrix}
2 \\
-1
\end{pmatrix}
$$

$$
{a} \cdot {b} = 3 \times 2 + 4 \times (-1) = 6 - 4 = 2
$$

### 問題4

ベクトル ${u}$ と ${v}$ があり、  

$$
{u} = 
\begin{pmatrix}
1 \\
0 \\
1
\end{pmatrix}, \quad
{v} = 
\begin{pmatrix}
0 \\
1 \\
1
\end{pmatrix}
$$

- (a) 内積 ${u} \cdot {v}$ を求めよ。  
- (b) ${u}$ と ${v}$ のなす角 $\theta$ を求めよ（内積と大きさの関係を利用する）：  
$$
\cos\theta = \frac{{u} \cdot {v}}{\|{u}\| \|{v}\|}
$$

### 問題5

2つのベクトルの cos類似度を求めなさい。

【参考】: https://scikit-learn.org/stable/modules/generated/sklearn.metrics.pairwise.cosine_similarity.html

In [3]:
import numpy as np
from sklearn.metrics.pairwise import cosine_similarity

# 問題で与えられたベクトル
u = np.array([[1, 0, 1]])
v = np.array([[0, 1, 1]])

# cos類似度の計算
cos_sim = cosine_similarity(u, v)[0][0]
print("cos類似度:", cos_sim)

cos類似度: 0.4999999999999999


### 問題6

問題5で求めた cos類似度から、2つのベクトルの角度を求めなさい。

【ヒント】: https://numpy.org/doc/stable/reference/generated/numpy.arccos.html

In [5]:
import numpy as np

# cos_sim から角度を計算
theta_rad = np.arccos(cos_sim)

# 角度を度に変換
theta_deg = np.degrees(theta_rad)

print("2つのベクトルのなす角）:", theta_deg)

2つのベクトルのなす角）: 60.00000000000001


## 第4回

### 問題1

`torch.nn.Embedding` を使って、トークンを埋め込みなさい。なお、トークンは乱数で与えても良い。

In [ ]:
import torch
import torch.nn as nn

size = 3
dim = 5

embed = nn.Embedding(num_embeddings=size, embedding_dim=dim)
tokens = torch.randint(low=0, high=size, size=(4,), dtype=torch.long)

embedded = embed(tokens)
print("トークン:", tokens)
print("埋め込みベクトル:\n", embedded)

トークン: tensor([1, 2, 1, 2])
埋め込みベクトル:
 tensor([[-0.0506, -1.7640, -0.3689, -1.5484,  0.4910],
        [-1.4328, -0.0059, -1.5416, -0.9160, -1.2234],
        [-0.0506, -1.7640, -0.3689, -1.5484,  0.4910],
        [-1.4328, -0.0059, -1.5416, -0.9160, -1.2234]],
       grad_fn=<EmbeddingBackward0>)


### 問題2

`torch.nn.MultiheadAttention` について、query, key, value を乱数で与えて、その出力を得なさい。

In [ ]:
import torch
import torch.nn as nn

embed_dim = 8
num_head = 2
mha = nn.MultiheadAttention(embed_dim=embed_dim, num_heads=num_head)

query = torch.rand(5, embed_dim)
key = torch.rand(5, embed_dim)
value = torch.rand(5, embed_dim)

attn_output, attn_output_weights = mha(query, key, value)

print("Attention出力\n", attn_output)
print("Attention重み\n", attn_output_weights)

Attention出力
 tensor([[ 0.2496, -0.0720, -0.0352,  0.3568,  0.2274, -0.1093, -0.1104, -0.2211],
        [ 0.2490, -0.0718, -0.0336,  0.3568,  0.2272, -0.1068, -0.1125, -0.2215],
        [ 0.2500, -0.0730, -0.0340,  0.3571,  0.2273, -0.1081, -0.1119, -0.2218],
        [ 0.2503, -0.0726, -0.0359,  0.3562,  0.2272, -0.1107, -0.1101, -0.2211],
        [ 0.2495, -0.0721, -0.0348,  0.3566,  0.2275, -0.1090, -0.1109, -0.2210]],
       grad_fn=<SqueezeBackward1>)
Attention重み
 tensor([[0.1980, 0.1931, 0.2108, 0.1977, 0.2004],
        [0.1940, 0.2018, 0.2073, 0.1917, 0.2052],
        [0.1913, 0.1970, 0.2137, 0.1921, 0.2060],
        [0.2016, 0.1920, 0.2107, 0.2033, 0.1924],
        [0.1989, 0.1971, 0.2075, 0.1984, 0.1981]], grad_fn=<SqueezeBackward1>)


### 問題3

`torch.nn.Transformer` に乱数を与えて、出力を得なさい。

In [ ]:
import torch
import torch.nn as nn

transformer = nn.Transformer(d_model=4, nhead=2)

src = torch.rand(2, 3, 4)
tgt = torch.rand(2, 3, 4)

output = transformer(src, tgt)

print("入力src:\n", src, "\n")
print("入力tgt:\n", tgt, "\n")

print("Transformer出力:", output)

入力src:
 tensor([[[0.3554, 0.9410, 0.9767, 0.2450],
         [0.9386, 0.7124, 0.4492, 0.4053],
         [0.8046, 0.7944, 0.6780, 0.0795]],

        [[0.5039, 0.1144, 0.1759, 0.6197],
         [0.4498, 0.9627, 0.4091, 0.3189],
         [0.6214, 0.8128, 0.2730, 0.6145]]]) 

入力tgt:
 tensor([[[0.0170, 0.7782, 0.0097, 0.7783],
         [0.1872, 0.3503, 0.7596, 0.5247],
         [0.6895, 0.9325, 0.4581, 0.0900]],

        [[0.3615, 0.8677, 0.6232, 0.6303],
         [0.1061, 0.3858, 0.3517, 0.5152],
         [0.0167, 0.5186, 0.9833, 0.8101]]]) 

Transformer出力: tensor([[[-1.5476,  0.3719, -0.0349,  1.2106],
         [-0.8521,  0.9679,  1.0215, -1.1373],
         [-1.1252,  1.3316,  0.5821, -0.7885]],

        [[-1.6282,  1.0968,  0.3136,  0.2178],
         [ 0.2089,  1.0223, -1.6532,  0.4220],
         [-1.6671,  0.2171,  0.4779,  0.9722]]],
       grad_fn=<NativeLayerNormBackward0>)


### 問題4

`sentence_transformers` を使って、いくつかの文章を埋め込み、それらの cos 類似度を測りなさい。

In [ ]:
from sentence_transformers import SentenceTransformer, util

# 1. 訓練済みのモデルをロード
model = SentenceTransformer("all-MiniLM-L6-v2")

# エンコードする文章のリスト
sentences = [
    "今日の天気は素晴らしいです。",
    "外はとても晴れています！",
    "彼はスタジアムへ車で行きました。",
    "The weather is lovely today.",
    "It's so sunny outside!",
    "He drove to the stadium.",
]

# 2. 文章を埋め込みベクトルに変換
embeddings = model.encode(sentences)
print(embeddings.shape)


# 3. 埋め込みの類似度を計算
similarities = util.pytorch_cos_sim(embeddings, embeddings)
print(similarities)


(6, 384)
tensor([[ 1.0000,  0.6759,  0.5684,  0.2042,  0.1317,  0.0087],
        [ 0.6759,  1.0000,  0.4978,  0.0987,  0.1227,  0.0720],
        [ 0.5684,  0.4978,  1.0000, -0.0114,  0.0335,  0.1189],
        [ 0.2042,  0.0987, -0.0114,  1.0000,  0.6660,  0.1046],
        [ 0.1317,  0.1227,  0.0335,  0.6660,  1.0000,  0.1411],
        [ 0.0087,  0.0720,  0.1189,  0.1046,  0.1411,  1.0000]])


## 第5回

言語生成モデル [distilgpt2](https://huggingface.co/distilbert/distilgpt2) を Google Colab の GPU 上で試しなさい。

<br>

参考コード：
- https://huggingface.co/distilbert/distilgpt2/colab
- https://huggingface.co/distilbert/distilgpt2#how-to-get-started-with-the-model

In [ ]:
import importlib, subprocess, sys
from transformers import AutoTokenizer, AutoModelForCausalLM, pipeline
from transformers import AutoTokenizer, AutoModelForCausalLM, pipeline
import torch

# DistilGPT-2 を使ってテキスト生成するセル
# (必要なパッケージが無ければインストールしてから読み込み)

try:
except Exception:
    subprocess.check_call([sys.executable, "-m", "pip", "install", "transformers"])
    importlib.invalidate_caches()


device = 0 if torch.cuda.is_available() else -1  # pipeline の device 引数: 0 は GPU、-1 は CPU

# モデルとトークナイザのロード
model_name = "distilgpt2"
tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForCausalLM.from_pretrained(model_name)

# テキスト生成パイプライン作成
gen = pipeline("text-generation", model=model, tokenizer=tokenizer, device=device)

# テスト用プロンプト（日本語・英語の例）
prompts = [
    "The future of AI is",
    "今日は素晴らしい天気です。午後の予定は",
]

# 生成パラメータの例
gen_kwargs = dict(
    max_length=80,
    do_sample=True,
    top_k=50,
    top_p=0.95,
    temperature=0.8,
    num_return_sequences=2
)

for p in prompts:
    print(f"=== Prompt: {p}")
    outputs = gen(p, **gen_kwargs)
    for i, out in enumerate(outputs, 1):
        # pipeline の返り値は dict で 'generated_text' キーに生成文が入る
        print(f"--- Output {i} ---")
        print(out["generated_text"])
    print()